# Generated by Django 3.1.1 on 2020-10-07 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('food', models.CharField(choices=[('B', 'Bamboo'), ('F', 'Fruits'), ('I', 'Insects'), ('S', 'Seeds'), ('N', 'Nectar')], default='B', max_length=1)),
                ('lemur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.lemur')),
            ],
        ),
    ]
