# Generated by Django 3.1.1 on 2020-10-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='date',
            field=models.DateField(verbose_name='Feeding date'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='food',
            field=models.CharField(choices=[('B', 'Bamboo'), ('F', 'Fruits'), ('S', 'Seeds'), ('N', 'Nectar')], default='B', max_length=1),
        ),
    ]
